
version: "3"
services:
  liongardroaragent:
    privileged: true
    image: "docker.io/radersolutions/liongard-roar"
    network_mode: host
    restart: always
    volumes:
      - "/usr/local/containers/roar/etc:/etc/roar"
