#!/bin/sh


. /etc/liongard/roar-container.conf 

curl -k https://$INSTANCE.app.liongard.com/api/v1/agents/scripts/setup-roar-agent/ -o setup-roar-agent
chmod 775 setup-roar-agent

alias roar=/usr/local/bin/roar 

sed -i -e "s#https://nodejs.org/dist/latest/#https://nodejs.org/dist/latest-v14.x/#g" setup-roar-agent 
sed -i -e "s#USER roar #USER /usr/local/bin/roar #g" setup-roar-agent 

USER=root ./setup-roar-agent --url "$INSTANCE.app.liongard.com" \
  --name "$AGENT_NAME" \
  --description "$DESCRIPTION" \
  --access-key $ACCESS_KEY \
  --access-secret $ACCESS_SECRET \
  --service-provider "$SERVICE_PROVIDER" \
  --environment "$ENVIRONMENT" 

sync
sleep 5

# Run roar pm2 in foreground
/usr/local/lib/node_modules/pm2/bin/pm2 resurrect --no-daemon